// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package my.test.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.test.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .my.test.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<my.test.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .my.test.proto.StudentResponse studentResponse = 1;</code>
   */
  my.test.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .my.test.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .my.test.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends my.test.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .my.test.proto.StudentResponse studentResponse = 1;</code>
   */
  my.test.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
